apiVersion: fn.kpt.dev/v1alpha1
kind: StarlarkRun
metadata:
  name: update-blog-host
params:
  host: myblog.com
source: |
  host = ctx.resource_list["functionConfig"]["params"]["host"]

  for resource in ctx.resource_list["items"]:
    if resource["kind"] == "Ingress":
      resource["spec"]["rules"][0]["host"] = host

    if resource["kind"] == "Deployment":
      container = resource["spec"]["template"]["spec"]["containers"][0]

      for env in container["env"]:
        if env["name"] == "GHOST_HOST":
          env["value"] = host
