# permissions for end users to view progressiverolloutstrategies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: progressiverolloutstrategy-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: rollouts
    app.kubernetes.io/part-of: rollouts
    app.kubernetes.io/managed-by: kustomize
  name: progressiverolloutstrategy-viewer-role
rules:
- apiGroups:
  - gitops.kpt.dev
  resources:
  - progressiverolloutstrategies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gitops.kpt.dev
  resources:
  - progressiverolloutstrategies/status
  verbs:
  - get
