---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - container.cnrm.cloud.google.com
  resources:
  - containerclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gitops.kpt.dev
  resources:
  - progressiverolloutstrategies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gitops.kpt.dev
  resources:
  - progressiverolloutstrategies/finalizers
  verbs:
  - update
- apiGroups:
  - gitops.kpt.dev
  resources:
  - progressiverolloutstrategies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gitops.kpt.dev
  resources:
  - remoterootsyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gitops.kpt.dev
  resources:
  - remoterootsyncs/finalizers
  verbs:
  - update
- apiGroups:
  - gitops.kpt.dev
  resources:
  - remoterootsyncs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gitops.kpt.dev
  resources:
  - rollouts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gitops.kpt.dev
  resources:
  - rollouts/finalizers
  verbs:
  - update
- apiGroups:
  - gitops.kpt.dev
  resources:
  - rollouts/status
  verbs:
  - get
  - patch
  - update
