# permissions for end users to edit rollouts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: rollout-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: rollouts
    app.kubernetes.io/part-of: rollouts
    app.kubernetes.io/managed-by: kustomize
  name: rollout-editor-role
rules:
- apiGroups:
  - gitops.kpt.dev
  resources:
  - rollouts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gitops.kpt.dev
  resources:
  - rollouts/status
  verbs:
  - get
